server:
  port: 8080
  servlet:
    context-path: /backend
spring:
  application:
    name: farellProject
  jmx:
    enabled: true
  jpa:
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://dhqpbiewrcyjje:1941f2f66a5cb396c50d37db62e2234b3fb7886ac14a23d8ff17c35218051638@ec2-34-234-240-121.compute-1.amazonaws.com:5432/ded0ev2lbsks8
    #${DS_PERDB_URL}
    username: dhqpbiewrcyjje
    #${R_DB_USR}
    password: 1941f2f66a5cb396c50d37db62e2234b3fb7886ac14a23d8ff17c35218051638
    #${R_DB_PWD}
    type: com.zaxxer.hikari.HikariDataSource
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

security:
  jwt:
    secret: "HOLAMUNDO"
    expiration: 36000