server:
  port: 8080
  servlet:
    context-path: /backend
spring:
  application:
    name: farellProject
  jmx:
    enabled: true
  jpa:
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://marbkbvolqtcpc:e80d54350398a9a0994ff83234103f0dac372c09041b2dcae3bc864e8fda26f9@ec2-3-224-164-189.compute-1.amazonaws.com:5432/d614g87ohbmeo7
    #${DS_PERDB_URL}
    username: marbkbvolqtcpc
    #${R_DB_USR}
    password: e80d54350398a9a0994ff83234103f0dac372c09041b2dcae3bc864e8fda26f9
    #${R_DB_PWD}
    type: com.zaxxer.hikari.HikariDataSource
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

security:
  jwt:
    secret: "HOLAMUNDO"
    expiration: 36000